spring.application.name=Projeto-Multidisciplinar-SGHSS
spring.datasource.url=jdbc:h2:mem:sghssdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.springframework.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true